/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
* Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
*/
package com.mycompany.gabun_program;
import javax.swing.JOptionPane;
/**
*
* @author CL2-PC
*/
public class receipt extends javax.swing.JFrame {

private String selectedProduct = "";
private int price = 0;

/**
* Creates new form receipt
*/
public receipt() {
initComponents();

// Initial values
lblSelectedCategory.setText("Selected Category: None");
lblSelectedProduct.setText("Selected Product: None");
lblPrice.setText("Price: ₱0");
lblSubtotal.setText("Subtotal: ₱0");
lblChange.setText("Change: ₱0");

txtQuantity.setText("0");
txtCash.setText("0");

// Products are not available until Snacks is selected
btnPiatos1.setEnabled(false);
btnNova.setEnabled(false);
btnGulaman.setEnabled(false);
btnPandan.setEnabled(false);

}

/**
* This method is called from within the constructor to initialize the form.
* WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor.
*/
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnSnacks = new javax.swing.JButton();
        btnDrinks = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        btnNova = new javax.swing.JButton();
        btnPandan = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblCash = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        btnAgain = new javax.swing.JButton();
        lblSelectedCategory = new javax.swing.JLabel();
        lblSelectedProduct = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnPiatos1 = new javax.swing.JButton();
        btnGulaman = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblTitle.setText("CANTEEN");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 104, 52));

        btnSnacks.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        btnSnacks.setText("[1] Snacks");
        btnSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnacksActionPerformed(evt);
            }
        });
        getContentPane().add(btnSnacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnDrinks.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        btnDrinks.setText("[2] Drinks");
        btnDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinksActionPerformed(evt);
            }
        });
        getContentPane().add(btnDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, 30));

        lblCategory.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblCategory.setText("Choose Category:");
        getContentPane().add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblProduct.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblProduct.setText("Product:");
        getContentPane().add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 30));

        btnNova.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        btnNova.setText("[2] NOVA - ₱25 ");
        btnNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaActionPerformed(evt);
            }
        });
        getContentPane().add(btnNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 140, -1));

        btnPandan.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        btnPandan.setText("[2] Pandan - ₱10");
        btnPandan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPandanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPandan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, -1));

        btnOrder.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 100, 60));

        lblQuantity.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblQuantity.setText("Qauantity:");
        getContentPane().add(lblQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 130, -1));

        lblCash.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblCash.setText("Cash:");
        getContentPane().add(lblCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));
        getContentPane().add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 130, -1));

        lblSubtotal.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblSubtotal.setText("Total: ₱0");
        getContentPane().add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        lblChange.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblChange.setText("Change: ₱0");
        getContentPane().add(lblChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        btnAgain.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        btnAgain.setText("Order Again?");
        btnAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgainActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, -1, 40));

        lblSelectedCategory.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblSelectedCategory.setText("Selected Product: None");
        getContentPane().add(lblSelectedCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        lblSelectedProduct.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lblSelectedProduct.setText("Selected Product: None");
        getContentPane().add(lblSelectedProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblPrice.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblPrice.setText("Price: ₱0");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnPiatos1.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        btnPiatos1.setText("[1] PIATOS - ₱22");
        btnPiatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiatos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPiatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        btnGulaman.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        btnGulaman.setText("[1] Gulaman - ₱15");
        btnGulaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGulamanActionPerformed(evt);
            }
        });
        getContentPane().add(btnGulaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnacksActionPerformed

   lblSelectedCategory.setText("Selected Category: Snacks");

    btnPiatos1.setEnabled(true);
    btnNova.setEnabled(true);

    btnGulaman.setEnabled(false);
    btnPandan.setEnabled(false);

    selectedProduct = "";
    price = 0;

    lblSelectedProduct.setText("Selected Product: None");
    lblPrice.setText("Price: ₱0"); // TODO add your handling code here:
}//GEN-LAST:event_btnSnacksActionPerformed

private void btnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinksActionPerformed

 lblSelectedCategory.setText("Selected Category: Drinks");

    btnPiatos1.setEnabled(false);
    btnNova.setEnabled(false);

    btnGulaman.setEnabled(true);
    btnPandan.setEnabled(true);

    selectedProduct = "";
    price = 0;

    lblSelectedProduct.setText("Selected Product: None");
    lblPrice.setText("Price: ₱0");
 // TODO add your handling code here:
}//GEN-LAST:event_btnDrinksActionPerformed

private void btnPandanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPandanActionPerformed

 selectedProduct = "Pandan";
    price = 10;

    lblSelectedProduct.setText("Selected Product: Pandan");
    lblPrice.setText("Price: ₱10");
}//GEN-LAST:event_btnPandanActionPerformed

private void btnNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaActionPerformed
selectedProduct = "Nova";
price = 25;

lblSelectedProduct.setText("Selected Product: Nova");
lblPrice.setText("Price: ₱25"); // TODO add your handling code here:
}//GEN-LAST:event_btnNovaActionPerformed

private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
try {


if (selectedProduct.equals("")) {
JOptionPane.showMessageDialog(
this,
"Please select a product first."
);
return;
}


int quantity = Integer.parseInt(txtQuantity.getText());

if (quantity <= 0) {
JOptionPane.showMessageDialog(
this,
"Quantity must be greater than 0."
);
return;
}


int subtotal = quantity * price;

lblSubtotal.setText("Subtotal: ₱" + subtotal);


int cash = Integer.parseInt(txtCash.getText());


while (cash < subtotal) {

JOptionPane.showMessageDialog(
this,
"Insufficient cash!\n"
+ "Subtotal: ₱" + subtotal
);

String newCash = JOptionPane.showInputDialog(
this,
"Enter enough cash:"
);

if (newCash == null) {
return;
}

cash = Integer.parseInt(newCash);
txtCash.setText(String.valueOf(cash));
}


int change = cash - subtotal;

lblChange.setText("Change: ₱" + change);


JOptionPane.showMessageDialog(
this,
"ORDER RECEIPT\n\n"
+ "Category: "
+ lblSelectedCategory.getText()
.replace("Selected Category: ", "")
+ "\nProduct: " + selectedProduct
+ "\nPrice: ₱" + price
+ "\nQuantity: " + quantity
+ "\nSubtotal: ₱" + subtotal
+ "\nCash: ₱" + cash
+ "\nChange: ₱" + change
);

} catch (NumberFormatException e) {

JOptionPane.showMessageDialog(
this,
"Please enter valid numbers."
);
} // TODO add your handling code here:
}//GEN-LAST:event_btnOrderActionPerformed

private void btnAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgainActionPerformed
act();
}//GEN-LAST:event_btnAgainActionPerformed

private void btnPiatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiatos1ActionPerformed
    selectedProduct = "Piatos";
    price = 22;

    lblSelectedProduct.setText("Selected Product: Piatos");
    lblPrice.setText("Price: ₱22");

}//GEN-LAST:event_btnPiatos1ActionPerformed

private void btnGulamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGulamanActionPerformed
    selectedProduct = "Gulaman";
    price = 15;

    lblSelectedProduct.setText("Selected Product: Gulaman");
    lblPrice.setText("Price: ₱15");// TODO add your handling code here:
}//GEN-LAST:event_btnGulamanActionPerformed

private void act() {

int answer = JOptionPane.showConfirmDialog(
this,
"Do you want to order again?",
"Order Again",
JOptionPane.YES_NO_OPTION

);

if (answer == JOptionPane.YES_OPTION) {

// Reset order
selectedProduct = "";
price = 0;

lblSelectedCategory.setText("Selected Category: None");
lblSelectedProduct.setText("Selected Product: None");
lblPrice.setText("Price: ₱0");
lblSubtotal.setText("Subtotal: ₱0");
lblChange.setText("Change: ₱0");

txtQuantity.setText("0");
txtCash.setText("0");

btnPandan.setEnabled(false);
btnNova.setEnabled(false);


return;

} else {

JOptionPane.showMessageDialog(
this,
"Thank you for ordering!"

);
System.exit(0);
}
}


/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>

/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new receipt().setVisible(true);
}
});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgain;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JButton btnGulaman;
    private javax.swing.JButton btnNova;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPandan;
    private javax.swing.JButton btnPiatos1;
    private javax.swing.JButton btnSnacks;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSelectedCategory;
    private javax.swing.JLabel lblSelectedProduct;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
