/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gabun_program;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class RPSUI extends javax.swing.JFrame {

    /**
     * Creates new form RPSUI
     */
    public RPSUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setLabel("VS");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 100, -1));
        txt1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, -1));

        jLabel1.setText("[2] = PAPER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel4.setText("PLAYER 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel5.setText("PLAYER 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel6.setText("[3] = SCISSOR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel7.setText("[1] = ROCK");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        int p1 = Integer.parseInt(txt1.getText());
        int p2 = Integer.parseInt(txt2.getText());
        
    if (p1 == 1 && p2 == 1){
    JOptionPane.showMessageDialog(rootPane,  "Draw", "title", JOptionPane.INFORMATION_MESSAGE);
}
else if (p1 == 1 && p2 == 2){
    JOptionPane.showMessageDialog(rootPane,  "Player 2 Wins", "title", JOptionPane.INFORMATION_MESSAGE);
}
else if (p1 == 1 && p2 == 3){
    JOptionPane.showMessageDialog(rootPane,  "Player 1 Wins", "title", JOptionPane.INFORMATION_MESSAGE);
}

else if (p1 == 2 && p2 == 1){
    JOptionPane.showMessageDialog(rootPane,  "Player 1 Wins", "title", JOptionPane.INFORMATION_MESSAGE);
}
else if (p1 == 2 && p2 == 2){
    JOptionPane.showMessageDialog(rootPane,  "Draw", "title", JOptionPane.INFORMATION_MESSAGE);
}
else if (p1 == 2 && p2 == 3){
    JOptionPane.showMessageDialog(rootPane,  "Player 2 Wins", "title", JOptionPane.INFORMATION_MESSAGE);
}

else if (p1 == 3 && p2 == 1){
    JOptionPane.showMessageDialog(rootPane,  "Player 2 Wins", "title", JOptionPane.INFORMATION_MESSAGE);
}
else if (p1 == 3 && p2 == 2){
    JOptionPane.showMessageDialog(rootPane,  "Player 1 Wins", "title", JOptionPane.INFORMATION_MESSAGE);
}
else if (p1 == 3 && p2 == 3){
    JOptionPane.showMessageDialog(rootPane,  "Draw", "title", JOptionPane.INFORMATION_MESSAGE);
}
else{
    System.out.println("Invalid input");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPSUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPSUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
